format = """
$directory\
$git_branch\
$git_status\
$git_state\
$fill\
$line_break\
$character\
"""

[character]
error_symbol = "[â¯](bold red)"
success_symbol = "[â¯](bold blue)"

[directory]
home_symbol = "ïŸ› "
read_only = " ğŸ”’"
style = "bold blue"

[directory.substitutions]
"Documents" = " ïœ˜ "
"Downloads" = " ïŒ "
"Music" = " ï¢† "
"Pictures" = " ïŸ¨ "
"Projects" = " ï’™ "
"Videos" = " ï‘‡ "

[fill]
symbol = "."
style = "bright-black"

[git_branch]
format = '[\[$branch $symbol\]]($style) '
style = "bold cyan"
symbol = "î‚ "

[git_status]
style = "bold purple"
